_quotes=[{:text=>"Life is about making an impact, not making an income.", :author=>"Kevin Kruse", :language=>"en"},
{:text=>"Whatever the mind of man can conceive and believe, it can achieve.", :author=>"Napoleon Hill", :language=>"en"},
{:text=>"Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference. ", :author=>"Robert Frost", :language=>"en"},
{:text=>"I attribute my success to this: I never gave or took any excuse.", :author=>"Florence Nightingale", :language=>"en"},
{:text=>"You miss 100% of the shots you don’t take.", :author=>"Wayne Gretzky", :language=>"en"},
{:text=>"I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.", :author=>"Michael Jordan", :language=>"en"},
{:text=>"The most difficult thing is the decision to act, the rest is merely tenacity.", :author=>"Amelia Earhart", :language=>"en"},
{:text=>"Every strike brings me closer to the next home run.", :author=>"Babe Ruth", :language=>"en"},
{:text=>"Definiteness of purpose is the starting point of all achievement.", :author=>"W. Clement Stone", :language=>"en"},
{:text=>"Life isn’t about getting and having, it’s about giving and being.", :author=>"Kevin Kruse", :language=>"en"},
{:text=>"Life is what happens to you while you’re busy making other plans.", :author=>"John Lennon", :language=>"en"},
{:text=>"We become what we think about.", :author=>"Earl Nightingale", :language=>"en"},
{:text=>"Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.", :author=>"Mark Twain", :language=>"en"},
{:text=>"Life is 10% what happens to me and 90% of how I react to it.", :author=>"Charles Swindoll", :language=>"en"},
{:text=>"The most common way people give up their power is by thinking they don’t have any.", :author=>"Alice Walker", :language=>"en"},
{:text=>"The mind is everything. What you think you become.", :author=>"Buddha", :language=>"en"},
{:text=>"The best time to plant a tree was 20 years ago. The second best time is now.", :author=>"Chinese Proverb", :language=>"en"},
{:text=>"An unexamined life is not worth living.", :author=>"Socrates", :language=>"en"},
{:text=>"Eighty percent of success is showing up.", :author=>"Woody Allen", :language=>"en"},
{:text=>"Your time is limited, so don’t waste it living someone else’s life.", :author=>"Steve Jobs", :language=>"en"},
{:text=>"Winning isn’t everything, but wanting to win is.", :author=>"Vince Lombardi", :language=>"en"},
{:text=>"I am not a product of my circumstances. I am a product of my decisions.", :author=>"Stephen Covey", :language=>"en"},
{:text=>"Every child is an artist.  The problem is how to remain an artist once he grows up.", :author=>"Pablo Picasso", :language=>"en"},
{:text=>"You can never cross the ocean until you have the courage to lose sight of the shore.", :author=>"Christopher Columbus", :language=>"en"},
{:text=>"I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", :author=>"Maya Angelou", :language=>"en"},
{:text=>"Whether you think you can or you think you can’t, you’re right.", :author=>"Henry Ford", :language=>"en"},
{:text=>"Either you run the day, or the day runs you.", :author=>"Jim Rohn", :language=>"en"},
{:text=>"The two most important days in your life are the day you are born and the day you find out why.", :author=>"Mark Twain", :language=>"en"},
{:text=>"Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.", :author=>"Johann Wolfgang von Goethe", :language=>"en"},
{:text=>"The best revenge is massive success.", :author=>"Frank Sinatra", :language=>"en"},
{:text=>"People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily.", :author=>"Zig Ziglar", :language=>"en"},
{:text=>"Life shrinks or expands in proportion to one’s courage.", :author=>"Anais Nin", :language=>"en"},
{:text=>"If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.", :author=>"Vincent Van Gogh", :language=>"en"},
{:text=>"There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", :author=>"Aristotle", :language=>"en"},
{:text=>"Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", :author=>"Jesus", :language=>"en"},
{:text=>"The only person you are destined to become is the person you decide to be.", :author=>"Ralph Waldo Emerson", :language=>"en"},
{:text=>"Go confidently in the direction of your dreams.  Live the life you have imagined.", :author=>"Henry David Thoreau", :language=>"en"},
{:text=>"When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", :author=>"Erma Bombeck", :language=>"en"},
{:text=>"Few things can help an individual more than to place responsibility on him, and to let him know that you trust him. ", :author=>"Booker T. Washington", :language=>"en"},
{:text=>"Certain things catch your eye, but pursue only those that capture the heart.", :author=>" Ancient Indian Proverb", :language=>"en"},
{:text=>"Believe you can and you’re halfway there.", :author=>"Theodore Roosevelt", :language=>"en"},
{:text=>"Everything you’ve ever wanted is on the other side of fear.", :author=>"George Addair", :language=>"en"},
{:text=>"We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", :author=>"Plato", :language=>"en"},
{:text=>"Teach thy tongue to say, “I do not know,” and thous shalt progress.", :author=>"Maimonides", :language=>"en"},
{:text=>" Start where you are. Use what you have.  Do what you can.", :author=>"Arthur Ashe", :language=>"en"},
{:text=>"When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life.", :author=>"John Lennon", :language=>"en"},
{:text=>"Fall seven times and stand up eight.", :author=>"Japanese Proverb", :language=>"en"},
{:text=>"When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", :author=>"Helen Keller", :language=>"en"},
{:text=>"Everything has beauty, but not everyone can see.", :author=>"Confucius", :language=>"en"},
{:text=>"How wonderful it is that nobody need wait a single moment before starting to improve the world.", :author=>"Anne Frank", :language=>"en"},
{:text=>"When I let go of what I am, I become what I might be.", :author=>"Lao Tzu", :language=>"en"},
{:text=>"Life is not measured by the number of breaths we take, but by the moments that take our breath away.", :author=>"Maya Angelou", :language=>"en"},
{:text=>"Happiness is not something readymade.  It comes from your own actions.", :author=>"Dalai Lama", :language=>"en"},
{:text=>"If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.", :author=>"Sheryl Sandberg", :language=>"en"},
{:text=>"First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.", :author=>"Aristotle", :language=>"en"},
{:text=>"You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground.", :author=>"Unknown", :language=>"en"},
{:text=>"We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", :author=>"Marie Curie", :language=>"en"},
{:text=>"Too many of us are not living our dreams because we are living our fears.", :author=>"Les Brown", :language=>"en"},
{:text=>"Challenges are what make life interesting and overcoming them is what makes life meaningful.", :author=>"Joshua J. Marine", :language=>"en"},
{:text=>"If you want to lift yourself up, lift up someone else.", :author=>"Booker T. Washington", :language=>"en"},
{:text=>"I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", :author=>"Leonardo da Vinci", :language=>"en"},
{:text=>"Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless.", :author=>"Jamie Paolinetti", :language=>"en"},
{:text=>"You take your life in your own hands, and what happens? A terrible thing, no one to blame.", :author=>"Erica Jong", :language=>"en"},
{:text=>"What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", :author=>"Bob Dylan", :language=>"en"},
{:text=>"I didn’t fail the test. I just found 100 ways to do it wrong.", :author=>"Benjamin Franklin", :language=>"en"},
{:text=>"In order to succeed, your desire for success should be greater than your fear of failure.", :author=>"Bill Cosby", :language=>"en"},
{:text=>"A person who never made a mistake never tried anything new.", :author=>" Albert Einstein", :language=>"en"},
{:text=>"The person who says it cannot be done should not interrupt the person who is doing it.", :author=>"Chinese Proverb", :language=>"en"},
{:text=>"There are no traffic jams along the extra mile.", :author=>"Roger Staubach", :language=>"en"},
{:text=>"It is never too late to be what you might have been.", :author=>"George Eliot", :language=>"en"},
{:text=>"You become what you believe.", :author=>"Oprah Winfrey", :language=>"en"},
{:text=>"I would rather die of passion than of boredom.", :author=>"Vincent van Gogh", :language=>"en"},
{:text=>"A truly rich man is one whose children run into his arms when his hands are empty.", :author=>"Unknown", :language=>"en"},
{:text=>"It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings. ", :author=>"Ann Landers", :language=>"en"},
{:text=>"If you want your children to turn out well, spend twice as much time with them, and half as much money.", :author=>"Abigail Van Buren", :language=>"en"},
{:text=>"Build your own dreams, or someone else will hire you to build theirs.", :author=>"Farrah Gray", :language=>"en"},
{:text=>"The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at.", :author=>"Jesse Owens", :language=>"en"},
{:text=>"Education costs money.  But then so does ignorance.", :author=>"Sir Claus Moser", :language=>"en"},
{:text=>"I have learned over the years that when one’s mind is made up, this diminishes fear.", :author=>"Rosa Parks", :language=>"en"},
{:text=>"It does not matter how slowly you go as long as you do not stop.", :author=>"Confucius", :language=>"en"},
{:text=>"If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.", :author=>"Oprah Winfrey", :language=>"en"},
{:text=>"Remember that not getting what you want is sometimes a wonderful stroke of luck.", :author=>"Dalai Lama", :language=>"en"},
{:text=>"You can’t use up creativity.  The more you use, the more you have.", :author=>"Maya Angelou", :language=>"en"},
{:text=>"Dream big and dare to fail.", :author=>"Norman Vaughan", :language=>"en"},
{:text=>"Our lives begin to end the day we become silent about things that matter.", :author=>"Martin Luther King Jr.", :language=>"en"},
{:text=>"Do what you can, where you are, with what you have.", :author=>"Teddy Roosevelt", :language=>"en"},
{:text=>"If you do what you’ve always done, you’ll get what you’ve always gotten.", :author=>"Tony Robbins", :language=>"en"},
{:text=>"Dreaming, after all, is a form of planning.", :author=>"Gloria Steinem", :language=>"en"},
{:text=>"It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live.", :author=>"Mae Jemison", :language=>"en"},
{:text=>"You may be disappointed if you fail, but you are doomed if you don’t try.", :author=>"Beverly Sills", :language=>"en"},
{:text=>"Remember no one can make you feel inferior without your consent.", :author=>"Eleanor Roosevelt", :language=>"en"},
{:text=>"Life is what we make it, always has been, always will be.", :author=>"Grandma Moses", :language=>"en"},
{:text=>"The question isn’t who is going to let me; it’s who is going to stop me.", :author=>"Ayn Rand", :language=>"en"},
{:text=>"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", :author=>"Henry Ford", :language=>"en"},
{:text=>"It’s not the years in your life that count. It’s the life in your years.", :author=>"Abraham Lincoln", :language=>"en"},
{:text=>"Change your thoughts and you change your world.", :author=>"Norman Vincent Peale", :language=>"en"},
{:text=>"Either write something worth reading or do something worth writing.", :author=>"Benjamin Franklin", :language=>"en"},
{:text=>"Nothing is impossible, the word itself says, “I’m possible!”", :author=>"Audrey Hepburn", :language=>"en"},
{:text=>"The only way to do great work is to love what you do.", :author=>"Steve Jobs", :language=>"en"},
{:text=>"If you can dream it, you can achieve it.", :author=>"Zig Ziglar", :language=>"en"},
{:text=>"Il est une bonne chose de lire des livres de citations, car les citations lorsqu’elles sont gravées dans la mémoire vous donnent de bonnes pensées", :author=>" Winston Churchill", :language=>"fr"},
{:text=>"Le plus grand plaisir de la vie est de réaliser ce que les autres vous pensent incapable de réaliser", :author=>" Walter Bagehot", :language=>"fr"},
{:text=>"Tout ce que vous désirez est là qui attend que vous le demandiez", :author=>" Tout ce que vous désirez vous désire également mais vous devez passer à l’action pour l’obtenir", :language=>"fr"},
{:text=>"Emporte dans ta mémoire, pour le reste de ton existence, les choses positives qui ont surgi au milieu des difficultés elles seront une preuve de tes capacités et te redonneront confiance devant tous les obstacles", :author=>" Paulo Coelho", :language=>"fr"},
{:text=>"C’est bon de ne pas regarder à la dépense de son énergie !", :author=>"Jules Renard", :language=>"fr"},
{:text=>"La formule sacrée du positivisme : l’amour pour principe, l’ordre pour base, et le progrès pour but", :author=>"Auguste Comte", :language=>"fr"},
{:text=>"'Apprenez à répéter le mot Tranquillité',' Non seulement il compte parmi les plus harmonieux de notre langue, mais il crée l’état d’esprit correspondant','Sérénité est un autre mot porteur de guérison',' Répétez-le lentement en vous imprégnant de son sens','Les mots de cette nature ont réellement un pouvoir apaisant','Norman Vincent Peale','Il y a plus de courage que de talent dans la plupart des réussites'", :author=>"Félix Leclerc", :language=>"fr"},
{:text=>"L’amour fait songer, vivre et croire il a pour réchauffer le coeur un rayon de plus que la gloire et ce rayon, c’est le bonheur", :author=>"Victor Hugo", :language=>"fr"},
{:text=>"Prenez en charge vos pensées, vous pouvez en faire ce que vous voulez", :author=>"Auteur anonyme", :language=>"fr"},
{:text=>"La plus grande découverte de notre génération a été de s’apercevoir qu’un homme peut changer sa vie en modifiant sa façon de penser", :author=>"Williams James", :language=>"fr"},
{:text=>"Votre vie peut changer quand vous changerez vos actions, et vos actions peuvent changer quand vous changerez votre manière de penser; si vous ne pouvez pas réussir, vous pouvez essayer; si vous pouvez essayer, vous pouvez réussir", :author=>"Anthony Robbins", :language=>"fr"},
{:text=>"Heureux les amants que nous sommes et qui demain, loin l’un de l’autre s’aimeront par dessus les hommes", :author=>"Jacques Brel", :language=>"fr"},
{:text=>"Quand tout est fichu, il y a encore le courage", :author=>"Daniel Pennac", :language=>"fr"},
{:text=>"Tous les gens qui réussissent rencontrent des gens qui réussissent de façon régulière, créant ainsi un mental collectif", :author=>"Napoleon Hill", :language=>"fr"},
{:text=>"La source de toute abondance ne se trouve pas à l’extérieur de vous, elle fait partie de ce que vous êtes, commencez cependant par reconnaître l’abondance à l’extérieur de vous. Voyez la plénitude de la vie, la chaleur du soleil sur votre peau, les magnifiques fleurs dans la vitrine du fleuriste, le fruit succulent dans lequel vous mordez ou l’abondante pluie qui tombe du ciel et vous trempe", :author=>"Eckhart Tolle", :language=>"fr"},
{:text=>"Aux grandes âmes, les grands challenges", :author=>"Anne Marquier", :language=>"fr"},
{:text=>"La pratique quotidienne de la gratitude est l’une des voies qu’empruntera la richesse pour venir à vous", :author=>"Wallace Wattles", :language=>"fr"},
{:text=>"La plénitude de la vie est dans tout", :author=>" Quand vous reconnaissez l’abondance qui est autour de vous, l’abondance latente en vous s’éveille", :language=>"fr"},
{:text=>"Tout ce que le mental de l’homme peut concevoir et croire, il peut le réaliser", :author=>"Napoleon Hill", :language=>"fr"},
{:text=>"Chaque pensée est une cause et chaque condition, un effet c’est pourquoi il est absolument essentiel que vous contrôliez vos pensées de manière à ne produire que des conditions désirées", :author=>"Charles F. Haanel", :language=>"fr"},
{:text=>"Doutez, si vous voulez, de celui qui vous aime. D’une femme ou d’un chien, mais non de l’amour même", :author=>"Alfred de Musset", :language=>"fr"},
{:text=>"Tout est une question d’attitude : il faut imprégner son esprit de pensées positives pour espérer profiter de cette force qui vit en chacun de nous", :author=>"Norman Vincent Peale", :language=>"fr"},
{:text=>"L’espérance est une échappatoire, la joie une affirmation positive du maintenant et de l’ici", :author=>"Antoine Spire", :language=>"fr"},
{:text=>"Aimer jusqu’à la déchirure. Aimer, même trop, même mal, Tenter, sans force et sans armure D’atteindre l’inaccessible étoile…", :author=>"Jacques Brel", :language=>"fr"},
{:text=>"Nous pouvons seulement être ce que nous pensons pouvoir être. Nous pouvons seulement avoir ce que nous pensons pouvoir posséder. Ce que nous faisons, ce que nous sommes, ce que nous avons, tout cela dépend de nos pensées", :author=>"R. Collier", :language=>"fr"},
{:text=>"La rêverie est le clair de lune de la pensée", :author=>"Jules Renard", :language=>"fr"},
{:text=>"Si Dieu est pour nous, qui sera contre nous ?", :author=>"Marc 2 : 1–12 et Romains 8 : 28–34", :language=>"fr"},
{:text=>"Préparez votre esprit à recevoir ce que la vie a de mieux à offrir", :author=>"Ernest Holmes", :language=>"fr"},
{:text=>"Le génie consiste à voir ce que tout le monde a vu et à penser ce que personne n’a pensé", :author=>"Albert Einstein", :language=>"fr"},
{:text=>"Tous les départs resserrent les coeurs qui se séparent", :author=>"Laurent Voulzy", :language=>"fr"},
{:text=>"S’aimer soi-même est le début d’une histoire d’amour qui durera toute la vie", :author=>"Oscar Wilde", :language=>"fr"},
{:text=>"On s’intéresse à ses membres comme parties de son corps, pourquoi pas aux hommes comme parties de l’humanité ?", :author=>"Dalaï Lama", :language=>"fr"},
{:text=>"Vous êtes maître de votre vie, et qu’importe votre prison, vous en avez les clefs", :author=>"Hervé Desbois", :language=>"fr"},
{:text=>"Tant qu’il y a de l’espoir, il y a de la vie !", :author=>"Jean Prieur", :language=>"fr"},
{:text=>"Les hommes connaissent tous l’utilité d’être utile, mais aucun ne connaît l’utilité d’être inutile", :author=>"Tchouang-Tseu", :language=>"fr"},
{:text=>"Vous devez croire en vous, même si vous êtes seul à le penser", :author=>" C’est ce qui fera de vous un gagnant", :language=>"fr"},
{:text=>"Dans chaque pensée, il y a une croyance… C’est VOUS qui créez cette croyance… C’est vous qui choisissez… Que vos croyances soient grandes et audacieuses", :author=>"Jack Canfield", :language=>"fr"},
{:text=>"Tes yeux sont mon Pérou, ma Golconde, mes Indes", :author=>"Louis Aragon", :language=>"fr"},
{:text=>"Ce qui compte ce n’est pas ce que l’on donne, mais l’amour avec lequel on le donne", :author=>"Mère Thérésa", :language=>"fr"},
{:text=>"Un être humain qui s’éteint, ce n’est pas un mortel qui finit, c’est un immortel qui commence", :author=>"Doris Lussier", :language=>"fr"},
{:text=>"Seul est grand celui qui transforme la voix du vent en un chant que son propre amour aura rendu plus doux", :author=>"Kahlil Gibran", :language=>"fr"},
{:text=>"On ne consent pas à ramer quand une force supérieure nous pousse à voler", :author=>"Helen Keller", :language=>"fr"},
{:text=>"Tous les jours et à tous points de vue, je vais de mieux en mieux", :author=>"Emile Coué", :language=>"fr"},
{:text=>"Nous nous rendons pitoyables ou nous nous rendons forts", :author=>" La quantité de travail à fournir est la même", :language=>"fr"},
{:text=>"Avoir un mental cent pour cent positif, c’est le secret", :author=>" La clé de toutes les victoires", :language=>"fr"},
{:text=>"La chance est la faculté de saisir les bonnes occasions", :author=>"Douglas MacArthur", :language=>"fr"},
{:text=>"L’amour, la seule passion qui cherche son bonheur dans celui d’un autre", :author=>"Alphonse Karr", :language=>"fr"},
{:text=>"Le secret de tout pouvoir, de tout accomplissement et de toute possession dépend de notre mode de pensée", :author=>"Charles F. Haanel", :language=>"fr"},
{:text=>"Notre esprit n’a pour limites que celles que nous lui reconnaissons", :author=>"Napoleon Hill", :language=>"fr"},
{:text=>"La GRANDEUR s’obtient uniquement par l’entretien constant de grandes pensées", :author=>"Wallace Wattles", :language=>"fr"},
{:text=>"Je puis tout par Celui qui me fortifie", :author=>"Philippiens 4,13", :language=>"fr"},
{:text=>"Il est probable que de nouveau canaux ou des canaux peu ordinaires de distribution s’ouvriront, et lorsque la loi entrera totalement en vigueur, vous constaterez que les choses que vous cherchez vous cherchent", :author=>"Charles F. Haanel", :language=>"fr"},
{:text=>"Il faut se concentrer sur ce qu’il nous reste et non sur ce qu’on a perdu", :author=>"Yann Arthus-Bertrand", :language=>"fr"},
{:text=>"Ce qui importe n’est pas l’événement en lui-même, mais l’interprétation qu’on en fait", :author=>"Mihaly Csikszentmihalyi", :language=>"fr"},
{:text=>"Rien n’est impossible, seules les limites de nos esprits définissent certaines choses comme inconcevables", :author=>"Marc Levy", :language=>"fr"},
{:text=>"Tout ce à quoi l’homme pense et croit peut se réaliser", :author=>"Napoleon Hill", :language=>"fr"},
{:text=>"Nous devons « être » avant de pouvoir « faire », et nous ne pouvons « faire » que dans la mesure où nous « sommes », et ce que nous « sommes » dépend de ce que nous « pensons »", :author=>"Charles F. Haanel", :language=>"fr"},
{:text=>"Ces cadeaux quotidiens qui nous arrivent sous la forme d’un sourire, d’un mot gentil, d’un message encourageant, nous pouvons les accueillir pour ce qu’ils sont, avec fierté et reconnaissance", :author=>"Marcelle Della Faille", :language=>"fr"},
{:text=>"L’homme ne peut atteindre une grande personnalité extérieure qu’en étant grand intérieurement", :author=>"Wallace Wattles", :language=>"fr"},
{:text=>"Le royaume de Dieu est au-dedans de vous", :author=>"Luc 17,21", :language=>"fr"},
{:text=>"Il n’existe que deux façons de vivre votre vie. L’une comme si rien n’était un miracle. L’autre comme si tout était un miracle", :author=>"Albert Einstein", :language=>"fr"},
{:text=>"Nous devons d’abord croire que notre désir est déjà accompli pour que son accomplissement suive", :author=>"Charles F. Haanel", :language=>"fr"},
{:text=>"Ce qui est plus triste qu’une oeuvre inachevée, c’est une oeuvre jamais commencée", :author=>"Christinna Rosseti", :language=>"fr"}]

_user=[{name: "julie", provider: "native", password: "julie", password_confirmation: "julie", disclaimer: "true" }]

_media=[
	{:wo_type=>"stretch", :location=>"unknown", :position=>"up", :link=>"https://player.vimeo.com/video/142349746"},
	{:wo_type=>"fit", :location=>"unknown", :position=>"up", :link=>"https://player.vimeo.com/video/142284568"},
	{:wo_type=>"stretch", :location=>"unknown", :position=>"sit", :link=>"https://player.vimeo.com/video/142160136"},
	{:wo_type=>"fit", :location=>"unknown", :position=>"sit", :link=>"https://player.vimeo.com/video/142130830"}
	]


Quote.destroy_all
Media.destroy_all
User.destroy_all
UserWorkoutsDone.destroy_all

_quotes.each do |quote_|
	Quote.create(quote_)
end

_media.each do |dat_|
	Media.create(dat_)
end

_user.each do |dat_|
	User.create(dat_)
end